name: Cleanup Past Events

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  cleanup-events:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run cleanup script
        run: node .github/scripts/cleanup-events.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add src/data/events.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "ci: remove past events" && git push)
